#!/usr/bin/env bun
// Builds generated/policy.mjs from the Bend accounting policy with the pinned
// compiler's official module emitter. `--check` verifies the committed artifact
// instead of writing it, so drift fails the gate.
import { mkdtempSync, readFileSync, rmSync, writeFileSync, mkdirSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { root, toolchain, resolveBendExecutable, resolveBendSource, assertPinnedCompiler } from "./bend-toolchain.mjs";

const target = join(root, "generated", "policy.mjs");
const check = process.argv.includes("--check");
const header = `// Generated by scripts/build-bend.mjs from engine.bend, audit.bend and batch.bend with Bend ${toolchain.version}.
// Do not edit by hand: run \`bun run build:bend\` and commit the result.
`;

async function emit() {
  const bend = assertPinnedCompiler(resolveBendExecutable());
  const source = resolveBendSource();
  const plugin = (await import(join(source, "bend2", "main.ts"))).default;
  const outdir = mkdtempSync(join(tmpdir(), "pi-worktime-build-"));
  try {
    const built = await Bun.build({ entrypoints: [join(root, "scripts", "bend-entry.ts")], outdir, target: "node", format: "esm", plugins: [plugin], naming: "policy.mjs" });
    if (!built.success) throw new Error(built.logs.map((log) => String(log)).join("\n"));
    // Bun banners each module with a path relative to the build cwd; keep the
    // artifact byte-identical wherever the build runs.
    const code = readFileSync(join(outdir, "policy.mjs"), "utf8")
      .replace(/^\/\/ .*\/([^/\\]+\.(?:bend|ts))$/gm, "// $1");
    if (/\bbun:/.test(code)) throw new Error("generated policy still depends on Bun; it must run in plain Node");
    return header + code;
  } finally { rmSync(outdir, { recursive: true, force: true }); }
}

const produced = await emit();
if (check) {
  const current = await Bun.file(target).text().catch(() => null);
  if (current !== produced) {
    console.error("generated/policy.mjs is missing or stale. Run `bun run build:bend` and commit the result.");
    process.exit(1);
  }
  console.log("generated policy is current");
} else {
  mkdirSync(join(root, "generated"), { recursive: true });
  writeFileSync(target, produced);
  console.log(`wrote generated/policy.mjs (${produced.length} bytes)`);
}
